package poly.app.core.entities;
// Generated Sep 26, 2018 4:18:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KhoaHoc generated by hbm2java
 */
public class KhoaHoc  implements java.io.Serializable {


     private Integer maKh;
     private int hocPhi;
     private int thoiLuong;
     private int soBuoiHoc;
     private Date ngayKg;
     private String ghiChu;
     private Date ngayTao;
     private NhanVien nhanVien;
     private ChuyenDe chuyenDe;
     private Set hocViens = new HashSet(0);

    public KhoaHoc() {
    }

	
    public KhoaHoc(int hocPhi, int thoiLuong, int soBuoiHoc, Date ngayKg, Date ngayTao, NhanVien nhanVien, ChuyenDe chuyenDe) {
        this.hocPhi = hocPhi;
        this.thoiLuong = thoiLuong;
        this.soBuoiHoc = soBuoiHoc;
        this.ngayKg = ngayKg;
        this.ngayTao = ngayTao;
        this.chuyenDe = chuyenDe;
        this.nhanVien = nhanVien;
    }
    public KhoaHoc(int hocPhi, int thoiLuong, int soBuoiHoc, Date ngayKg, String ghiChu, Date ngayTao, NhanVien nhanVien, ChuyenDe chuyenDe, Set hocViens) {
       this.hocPhi = hocPhi;
       this.thoiLuong = thoiLuong;
       this.soBuoiHoc = soBuoiHoc;
       this.ngayKg = ngayKg;
       this.ghiChu = ghiChu;
       this.ngayTao = ngayTao;
       this.chuyenDe = chuyenDe;
       this.nhanVien = nhanVien;
       this.hocViens = hocViens;
    }
   
    public Integer getMaKh() {
        return this.maKh;
    }
    
    public void setMaKh(Integer maKh) {
        this.maKh = maKh;
    }
    public ChuyenDe getChuyenDe() {
        return this.chuyenDe;
    }
    
    public void setChuyenDe(ChuyenDe chuyenDe) {
        this.chuyenDe = chuyenDe;
    }
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    public int getHocPhi() {
        return this.hocPhi;
    }
    
    public void setHocPhi(int hocPhi) {
        this.hocPhi = hocPhi;
    }
    public int getThoiLuong() {
        return this.thoiLuong;
    }
    
    public void setThoiLuong(int thoiLuong) {
        this.thoiLuong = thoiLuong;
    }
    public int getSoBuoiHoc() {
        return this.soBuoiHoc;
    }
    
    public void setSoBuoiHoc(int soBuoiHoc) {
        this.soBuoiHoc = soBuoiHoc;
    }
    public Date getNgayKg() {
        return this.ngayKg;
    }
    
    public void setNgayKg(Date ngayKg) {
        this.ngayKg = ngayKg;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Set getHocViens() {
        return this.hocViens;
    }
    
    public void setHocViens(Set hocViens) {
        this.hocViens = hocViens;
    }




}


