package poly.app.core.entities;
// Generated Sep 21, 2018 5:51:44 PM by Hibernate Tools 4.3.1



/**
 * MaXacNhan generated by hbm2java
 */
public class MaXacNhan  implements java.io.Serializable {


     private String maNv;
     private NhanVien nhanVien;
     private String maXacNhan;

    public MaXacNhan() {
    }

    public MaXacNhan(NhanVien nhanVien, String maXacNhan) {
       this.nhanVien = nhanVien;
       this.maXacNhan = maXacNhan;
    }
   
    public String getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(String maNv) {
        this.maNv = maNv;
    }
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    public String getMaXacNhan() {
        return this.maXacNhan;
    }
    
    public void setMaXacNhan(String maXacNhan) {
        this.maXacNhan = maXacNhan;
    }




}


