package poly.app.core.entities;
// Generated Oct 7, 2018 2:44:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NguoiHoc generated by hbm2java
 */
public class NguoiHoc  implements java.io.Serializable {


     private String maNh;
     private NhanVien nhanVien;
     private String hoTen;
     private Date ngaySinh;
     private boolean gioiTinh;
     private String dienThoai;
     private String email;
     private String ghiChu;
     private Date ngayDk;
     private String hinh;
     private Set hocViens = new HashSet(0);

    public NguoiHoc() {
    }

	
    public NguoiHoc(String maNh, NhanVien nhanVien, String hoTen, Date ngaySinh, boolean gioiTinh, String dienThoai, String email, Date ngayDk) {
        this.maNh = maNh;
        this.nhanVien = nhanVien;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.dienThoai = dienThoai;
        this.email = email;
        this.ngayDk = ngayDk;
    }
    public NguoiHoc(String maNh, NhanVien nhanVien, String hoTen, Date ngaySinh, boolean gioiTinh, String dienThoai, String email, String ghiChu, Date ngayDk, String hinh, Set hocViens) {
       this.maNh = maNh;
       this.nhanVien = nhanVien;
       this.hoTen = hoTen;
       this.ngaySinh = ngaySinh;
       this.gioiTinh = gioiTinh;
       this.dienThoai = dienThoai;
       this.email = email;
       this.ghiChu = ghiChu;
       this.ngayDk = ngayDk;
       this.hinh = hinh;
       this.hocViens = hocViens;
    }
   
    public String getMaNh() {
        return this.maNh;
    }
    
    public void setMaNh(String maNh) {
        this.maNh = maNh;
    }
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Date getNgayDk() {
        return this.ngayDk;
    }
    
    public void setNgayDk(Date ngayDk) {
        this.ngayDk = ngayDk;
    }
    public String getHinh() {
        return this.hinh;
    }
    
    public void setHinh(String hinh) {
        this.hinh = hinh;
    }
    public Set getHocViens() {
        return this.hocViens;
    }
    
    public void setHocViens(Set hocViens) {
        this.hocViens = hocViens;
    }




}


