package poly.app.core.entities;
// Generated Sep 20, 2018 2:53:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NguoiHoc generated by hbm2java
 */
public class NguoiHoc  implements java.io.Serializable {


     private String maNh;
     private NhanVien nhanVien;
     private String hoTen;
     private Date ngaySinh;
     private boolean gioiTinh;
     private String dienThoai;
     private String email;
     private String ghiChu;
     private Date ngayDk;
     private Set<HocVien> hocViens = new HashSet<HocVien>(0);

    public NguoiHoc() {
    }

	
    public NguoiHoc(String maNh, NhanVien nhanVien, String hoTen, Date ngaySinh, boolean gioiTinh, String dienThoai, String email, Date ngayDk) {
        this.maNh = maNh;
        this.nhanVien = nhanVien;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.dienThoai = dienThoai;
        this.email = email;
        this.ngayDk = ngayDk;
    }
    public NguoiHoc(String maNh, NhanVien nhanVien, String hoTen, Date ngaySinh, boolean gioiTinh, String dienThoai, String email, String ghiChu, Date ngayDk, Set<HocVien> hocViens) {
       this.maNh = maNh;
       this.nhanVien = nhanVien;
       this.hoTen = hoTen;
       this.ngaySinh = ngaySinh;
       this.gioiTinh = gioiTinh;
       this.dienThoai = dienThoai;
       this.email = email;
       this.ghiChu = ghiChu;
       this.ngayDk = ngayDk;
       this.hocViens = hocViens;
    }
   
    public String getMaNh() {
        return this.maNh;
    }
    
    public void setMaNh(String maNh) {
        this.maNh = maNh;
    }
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Date getNgayDk() {
        return this.ngayDk;
    }
    
    public void setNgayDk(Date ngayDk) {
        this.ngayDk = ngayDk;
    }
    public Set<HocVien> getHocViens() {
        return this.hocViens;
    }
    
    public void setHocViens(Set<HocVien> hocViens) {
        this.hocViens = hocViens;
    }




}


