package poly.app.core.entities;
// Generated Oct 7, 2018 2:44:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhanVien generated by hbm2java
 */
public class NhanVien  implements java.io.Serializable {


     private String maNv;
     private String matKhau;
     private String hoTen;
     private Date ngaySinh;
     private boolean gioiTinh;
     private String dienThoai;
     private String email;
     private String diaChi;
     private String hinh;
     private boolean vaiTro;
     private Set khoaHocs = new HashSet(0);
     private MaXacNhan maXacNhan;
     private Set nguoiHocs = new HashSet(0);

    public NhanVien() {
    }

	
    public NhanVien(String maNv, String matKhau, String hoTen, Date ngaySinh, boolean gioiTinh, String dienThoai, String email, String diaChi, boolean vaiTro) {
        this.maNv = maNv;
        this.matKhau = matKhau;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.dienThoai = dienThoai;
        this.email = email;
        this.diaChi = diaChi;
        this.vaiTro = vaiTro;
    }
    public NhanVien(String maNv, String matKhau, String hoTen, Date ngaySinh, boolean gioiTinh, String dienThoai, String email, String diaChi, String hinh, boolean vaiTro, Set khoaHocs, MaXacNhan maXacNhan, Set nguoiHocs) {
       this.maNv = maNv;
       this.matKhau = matKhau;
       this.hoTen = hoTen;
       this.ngaySinh = ngaySinh;
       this.gioiTinh = gioiTinh;
       this.dienThoai = dienThoai;
       this.email = email;
       this.diaChi = diaChi;
       this.hinh = hinh;
       this.vaiTro = vaiTro;
       this.khoaHocs = khoaHocs;
       this.maXacNhan = maXacNhan;
       this.nguoiHocs = nguoiHocs;
    }
   
    public String getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(String maNv) {
        this.maNv = maNv;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getHinh() {
        return this.hinh;
    }
    
    public void setHinh(String hinh) {
        this.hinh = hinh;
    }
    public boolean getVaiTro() {
        return this.vaiTro;
    }
    
    public void setVaiTro(boolean vaiTro) {
        this.vaiTro = vaiTro;
    }
    public Set getKhoaHocs() {
        return this.khoaHocs;
    }
    
    public void setKhoaHocs(Set khoaHocs) {
        this.khoaHocs = khoaHocs;
    }
    public MaXacNhan getMaXacNhan() {
        return this.maXacNhan;
    }
    
    public void setMaXacNhan(MaXacNhan maXacNhan) {
        this.maXacNhan = maXacNhan;
    }
    public Set getNguoiHocs() {
        return this.nguoiHocs;
    }
    
    public void setNguoiHocs(Set nguoiHocs) {
        this.nguoiHocs = nguoiHocs;
    }




}


